description: A Category
properties:
  id:
    description: A unique identifier for the Category.
    type: integer
    example: 3
  name:
    description: A unique name for the Category.
    type: string
    example: Hardware
  description:
    description: A description for the Category.
    type: string
    example: Hardware Items
  created_at:
    description: The date when the Category was first created.
    type: datetime
    example: 2016-12-02T15:01:12Z
  updated_at:
    description: The date when the Category was last modified.
    type: datetime
    example: 2016-12-06T12:33:52Z