description: A Category
properties:
  id:
    description: A unique identifier for the Category.
    type: integer
    example: 3
  name:
    description: A unique name for the Category.
    type: string
    example: Hardware
  description:
    description: A description for the Category.
    type: string
    example: Hardware Items