description: The resource for a Category to be created.
properties:
  id:
    required: false
    description: A unique identifier for the Category.
    type: integer
    example: 21
  name:
    description: A unique name for the Category.
    type: string
    example: Hardware
  description:
    description: A description for the Category.
    type: string
    example: Hardware items