description: A Customer.
properties:
  id:
    description: A unique identifier for the Customer.
    type: integer
    example: 21
  name:
    description: A unique name for the Customer.
    type: string
    example: Custer McCustomer & Co.
  description:
    description: A description for the Customer.
    type: string
    example: The buying kind.
  created_at:
    description: The date when the Customer was first created.
    type: datetime
    example: 2016-12-02T15:01:12Z
  updated_at:
    description: The date when the Customer was last modified.
    type: datetime
    example: 2016-12-06T12:33:52Z