description: The resource for a Customer to be created or modified.
properties:
  id:
    required: false
    description: A unique identifier for the Customer.
    type: integer
    example: 21
  name:
    description: A unique name for the Customer.
    type: string
    example: Custer McCustomer & Co.
  description:
    description: A description for the Customer.
    type: string
    example: The buying kind.