description: A Customer.
properties:
  id:
    description: A unique identifier for the Customer.
    type: integer
    example: 21
  name:
    description: A unique name for the Customer.
    type: string
    example: Custer McCustomer & Co.
  description:
    description: A description for the Customer.
    type: string
    example: The buying kind.