description: A summarized description of a Product
properties:
  id:
    description: A unique identifier for the Product.
    type: integer
    example: 27
  name:
    description: A unique name for the Product.
    type: string
    example: Keyboard
  description:
    description: A description for the Product.
    type: string
    example: Wireless standard QWERTY keyboard
