description: The resource for a Product offer to be created or modified.
properties:
  id:
    required: false
    description: A unique identifier for the Product offer.
    type: integer
    example: 72
  product_id:
    description: The ID of the purchased product.
    type: integer
    example: 12
  provider_id:
    description: The ID of the provider from who the product is purchased.
    type: integer
    example: 2
  unit_price:
    description: The price per unit of the product.
    type: number
    example: 9.95
  delivery:
    required: false
    description: The estimated time (units TBD) the provider will take to fulfill an order.
    type: integer
    example: 48