description: The resource for a Provider to be created.
properties:
  id:
    description: A unique identifier for the Provider.
    type: integer
    example: 2
  name:
    description: A unique name for the Provider.
    type: string
    example: ACME
  description:
    description: A description for the Provider.
    type: string
    example: As seen in the Road Runner