description: A Purchase order
properties:
  id:
    required: false
    description: A unique identifier for the Purchase order.
    type: integer
    example: 610
  comments:
    description: Comments regarding the order.
    type: string
    example: "Expect very big boxes."