description: A Purchase order
properties:
  id:
    description: A unique identifier for the Purchase order.
    type: integer
    example: 610
  comments:
    description: Comments regarding the order.
    type: string
    example: "Expect very big boxes."
  state:
    description: The state of the Purchase order (true if pending, false otherwise)
    type: boolean
    example: true