description: A Purchase order
properties:
  id:
    description: A unique identifier for the Purchase order.
    type: integer
    example: 610
  comments:
    description: Comments regarding the order.
    type: string
    example: "Expect very big boxes."
  state:
    description: The state of the Purchase order (true if pending, false otherwise)
    type: boolean
    example: true
  created_at:
    description: The date when the Purchase order was first created.
    type: datetime
    example: 2016-12-02T15:01:12Z
  updated_at:
    description: The date when the Purchase order was last modified.
    type: datetime
    example: 2016-12-06T12:33:52Z