description: A Tag
properties:
  name:
    description: A unique name for the Tag.
    type: string
    example: Discounted
  created_at:
    description: The date when the Tag was first created.
    type: datetime
    example: 2016-12-02T15:01:12Z
  updated_at:
    description: The date when the Tag was last modified.
    type: datetime
    example: 2016-12-06T12:33:52Z