#%RAML 1.0
title: SMAPP

baseUri: http://localhost:8000/api/{version}
version: v1
mediaType: application/json
protocols:
  - HTTP

securedBy: basicAuth
securitySchemes:
  basicAuth:
    description: |
      Authentication for the use of the API is by using the Authorization Header with the API Token provided on installation.
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: |
            Used to send the API Token provided by the app instance
          type: string
          example: Bearer DrVs32TUurjFPmTXuNP9b2dO7uSOny14ZsbYtpANNdeMiVvglgX61cq2b6nO
      responses:
        401:
          description: |
            Unauthorized. The API Token provided is not correct or is not being sent

documentation:
  - title: Documentation for the SMAPP API
    content: |
      Specification and instructions for the usage of the SMAPP API.
      

/products:
  !include resources/products.raml

/categories:
  !include resources/categories.raml

/stocks:
  !include resources/stocks.raml

/tags:
  !include resources/tags.raml

/providers:
  !include resources/providers.raml

/customers:
  !include resources/customers.raml

/purchaseorders:
  !include resources/purchaseorders.raml

types:

  ProductResource:
    !include types/productresource.raml

  Product:
    !include types/product.raml

  ProductSummary:
    !include types/productsummary.raml

  CategoryResource:
    !include types/categoryresource.raml

  Category:
    !include types/category.raml

  TagResource:
    !include types/tagresource.raml

  Tag:
    !include types/tag.raml

  Stock:
    !include types/stock.raml

  ProviderResource:
    !include types/providerresource.raml

  Provider:
    !include types/provider.raml

  CustomerResource:
    !include types/customerresource.raml

  Customer:
    !include types/customer.raml

  PurchaseOrderResource:
    !include types/purchaseorderresource.raml

  PurchaseOrder:
    !include types/purchaseorder.raml

  PurchaseLine:
    !include types/purchaseline.raml

  SaleOrder:
    !include types/saleorder.raml
