#%RAML 1.0
title: SMAPP

baseUri: http://smapp.sorters.io/api/{version}
version: v1
mediaType: application/json
protocols:
  - HTTP
documentation:
  - title: Documentation for the SMAPP API
    content: |
      Authentication for the use of the API is by using the Authorization Header with the API Token provided on installation.

/products:
  !include resources/products.raml

/categories:
  !include resources/categories.raml

/stocks:
  !include resources/stocks.raml

/tags:
  !include resources/tags.raml

/providers:
  !include resources/providers.raml

/customers:
  !include resources/customers.raml

types:

  ProductResource:
    !include types/productresource.raml

  Product:
    !include types/product.raml

  ProductSummary:
    !include types/productsummary.raml

  CategoryResource:
    !include types/categoryresource.raml

  Category:
    !include types/category.raml

  TagResource:
    !include types/tagresource.raml

  Tag:
    !include types/tag.raml

  Stock:
    !include types/stock.raml

  ProviderResource:
    !include types/providerresource.raml

  Provider:
    !include types/provider.raml

  CustomerResource:
    !include types/customerresource.raml

  Customer:
    !include types/customer.raml

  PurchaseLine:
    !include types/purchaseline.raml
