  get:
    description: List all the available Categories.
    responses:
      200:
        description: A list of Categories.
        body:
          type: Category[]
      401:
        description: Unauthorized

  post:
    description: Create or Modify a Category. If a parameter 'id' for an existing Category is passed in the body the resource will update the existing Category.
    body:
      type: CategoryResource
    responses:
      200:
        description: The ID of the Category created or modified.
        body:
          type: integer
          example: 3
      400:
        description: Bad request
      401:
        description: Unauthorized

  /{id}:
    uriParameters:
      id:
        description: The unique identifier for the Category.
        type: integer
        example: 3

    get:
      description: List details of a Category.
      responses:
        200:
          description: The details of a Category.
          body:
            type: Category
        401:
          description: Unauthorized
        404:
          description: Not found

    delete:
      description: Deletes the Category.
      responses:
        200:
          description: The deletion was successful.
        401:
          description: Unauthorized

    /products:

      get:
        description: Lists all the Products that belong to the Category.
        responses:
          200:
            description: A list of all the Products that belong to the Category.
            body:
              type: Category[]
          401:
            description: Unauthorized
          404:
            description: Not found

      post:
        body:
          application/json:
            example: |
              "products":"21,22,23,24"
        description: Assign the Products to the Category
        responses:
          200:
            description: The assignment was successful